# Test your FastAPI endpoints

###

GET {{host_url}}:8000/
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        console.log("Response Body:", response.body);
    });
%}
###

POST http://127.0.0.1:8000/users
Content-Type: application/json

{
  "username": "{{username}}",
  "email": "{{email}}",
  "password": "secretthding68"
}

> {%
  const username = response.body.username;
  client.global.set("username", username);
  const password = request.body().password;
  client.global.set("password", password);
  console.log("Created User:", username);

%}

###

POST http://localhost:8000/auth/token/
Content-Type: application/x-www-form-urlencoded

username=asdfaddsdffa&password=secretthding68

> {%
    client.test("Token obtained successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.access_token, "Access token is missing in the response");
    });
    const access_token = response.body.access_token;
    client.global.set("access_token", access_token);
    console.log("Access Token:", access_token);
%}

###
GET http://localhost:8000/auth/users/me
Authorization: Bearer {{access_token}}

> {%
    response.status === 200;
  const user_id = response.body.id;
  client.global.set("user_id", user_id);
%}

###

POST http://localhost:8001/todo
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Buy groceries",
  "description": "Milk, Bread, Eggs"
}

> {%
  const todo_id = response.body.id;
  client.global.set("todo_id", todo_id);
%}

###
